<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Order ID_order_id</name>
   <tag></tag>
   <elementGuidId>ab7d0f8f-91ab-496d-8e8e-c5ab7af84c41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CheckOrderFrm_order_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CheckOrderFrm_order_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53a4ba77-946f-4aba-8920-2eb5e5719104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e488afce-ea06-41a9-924b-4b12728389d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order_id</value>
      <webElementGuid>f19be12c-244a-4ae0-9a0c-18d23a6c65ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CheckOrderFrm_order_id</value>
      <webElementGuid>4448c3f6-ae1e-46ca-9c60-7a5ffeadac48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>219189e0-7de2-44d3-b25c-ff9aacdf071f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CheckOrderFrm_order_id&quot;)</value>
      <webElementGuid>763a523c-51a6-4d29-a306-3200bc9a3d31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CheckOrderFrm_order_id']</value>
      <webElementGuid>8a8ec640-9477-4d00-ac13-623540ca8c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CheckOrderFrm']/div/fieldset/div/div/input</value>
      <webElementGuid>85a127e1-4455-4b18-a9c4-2e96193976bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>63d9afa7-87bb-4890-94a7-96a68cee567d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'order_id' and @id = 'CheckOrderFrm_order_id']</value>
      <webElementGuid>8dfc2bf4-3aea-4148-8b7a-7b18d2ceb7d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
