<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Back to top</name>
   <tag></tag>
   <elementGuidId>8d0fec0e-0871-457f-b317-6ac7a1a22b5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='gotop']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gotop</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6a908aa8-65e7-4840-a809-fcb90b598459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gotop</value>
      <webElementGuid>e29f452d-5e42-4b0e-a24b-3cd034000c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5562c992-5a7a-4249-8c60-4754311a9807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back to top</value>
      <webElementGuid>da9115ca-72b1-4172-8c4b-3c6f03b66501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gotop&quot;)</value>
      <webElementGuid>dcd86aa9-0b97-4a0d-90e2-40c7a4e42f13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='gotop']</value>
      <webElementGuid>a695bae4-4565-45d8-80be-1cffba7b0aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='footer']/footer/a</value>
      <webElementGuid>95ebdbdb-1af1-469c-983b-5ac0dd1f7001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Back to top')]</value>
      <webElementGuid>0550e0c8-e61d-4b13-9495-9f51d3dc3ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AbanteCart'])[1]/following::a[1]</value>
      <webElementGuid>15b62359-2fa3-483a-b1b1-e6b937ce9cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Back to top']/parent::*</value>
      <webElementGuid>3b667dd5-47de-4315-bfe7-c48552091b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[26]</value>
      <webElementGuid>73804d42-675e-45c9-b427-6ad5f7e9cf32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/a</value>
      <webElementGuid>168fed81-9bf4-4f64-a150-c873a66f11e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'gotop' and @href = '#' and (text() = 'Back to top' or . = 'Back to top')]</value>
      <webElementGuid>5bf9ab35-a404-451d-8296-cbe06f854e1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
