<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>97aaa82c-59f9-42cc-8e29-3c57c6bc35a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='maincontainer']/div/div/div/div/ul/li[4]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>895f177a-33a3-4345-b04b-c4350fa2b9f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//sewriveting.ca/store/image/thumbnails/18/73/demo_product_49_1_png-100146-120x120.png</value>
      <webElementGuid>cca5f0b2-36da-4768-b5ee-0bc77eea195d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>98184f7f-53f0-4504-9f29-44b79938e0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>b981b0c5-e20c-4613-a51a-24a5623cfa4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontainer&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;col-md-12 col-xs-12 mt20&quot;]/div[1]/div[@class=&quot;contentpanel&quot;]/ul[@class=&quot;thumbnails row&quot;]/li[@class=&quot;col-md-2 col-sm-2 col-xs-6 align_center&quot;]/a[1]/img[1]</value>
      <webElementGuid>1eeed74b-de10-434f-b755-35927637c9ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontainer']/div/div/div/div/ul/li[4]/a/img</value>
      <webElementGuid>eb680c9b-bc27-4803-8db3-459fbedb63d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/img</value>
      <webElementGuid>2a76a8fb-3767-4afb-9b57-bb5a2fb77aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//sewriveting.ca/store/image/thumbnails/18/73/demo_product_49_1_png-100146-120x120.png']</value>
      <webElementGuid>614c5736-e274-4d7d-a2e3-ed12f28ef424</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
