<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cart</name>
   <tag></tag>
   <elementGuidId>8f135ebf-f695-43e8-b22f-476f735ef06e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='main_menu']/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_menu > li.dropdown > a.top.nobackground</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c93989b9-0a58-4fd7-8eb1-cd4b0e1a0aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top nobackground</value>
      <webElementGuid>b3d4897e-126a-4863-9e8e-2eaec32b3702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://automationteststore.com/index.php?rt=checkout/cart</value>
      <webElementGuid>8b3bf8dd-cfd3-49b4-a72e-ec94d83ef08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Cart</value>
      <webElementGuid>cdaaf04d-f185-4406-a3bd-594272959b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_menu&quot;)/li[@class=&quot;dropdown&quot;]/a[@class=&quot;top nobackground&quot;]</value>
      <webElementGuid>dfdbbcd8-1716-431d-96b9-403086b0d8b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='main_menu']/li[3]/a</value>
      <webElementGuid>84bd89db-1e01-4149-b0fb-5572c024cbe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Your Order'])[2]/following::a[1]</value>
      <webElementGuid>80590a8a-ce6c-4652-a01e-3e6bd02ebba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/following::a[2]</value>
      <webElementGuid>10809450-3d4e-404d-a607-9558a419e96d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[2]/preceding::a[1]</value>
      <webElementGuid>f075810d-0a9a-4bc4-beea-969ad48fd811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://automationteststore.com/index.php?rt=checkout/cart')])[4]</value>
      <webElementGuid>fb63d83f-a267-425d-a468-072ac766340e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/ul/li[3]/a</value>
      <webElementGuid>f84585c2-b6d1-4e4d-b967-c634fbe35aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://automationteststore.com/index.php?rt=checkout/cart' and (text() = ' Cart' or . = ' Cart')]</value>
      <webElementGuid>dd389561-42f1-47cc-a7fc-e92f8390e477</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
