<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Featured</name>
   <tag></tag>
   <elementGuidId>12ffc667-18a8-42fd-82e3-9ccca56b5e75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block_frame_featured_2639']/h1/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.maintext</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>12b8440f-7f34-4593-abb2-e8041ad8e885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>maintext</value>
      <webElementGuid>7e1dacfe-2180-44c6-8213-83409f776500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Featured</value>
      <webElementGuid>60379460-3f9e-4dc6-9a2d-2ad4c5874217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block_frame_featured_2639&quot;)/h1[@class=&quot;heading1&quot;]/span[@class=&quot;maintext&quot;]</value>
      <webElementGuid>a81a4f95-9a79-43ff-91b3-ec94b453d669</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block_frame_featured_2639']/h1/span</value>
      <webElementGuid>40ccb8a4-c053-4e8a-9d9b-79ccd6852233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to web store!'])[1]/following::span[1]</value>
      <webElementGuid>3356e622-320d-4810-873a-e87290a47e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See Our Most featured Products'])[1]/preceding::span[1]</value>
      <webElementGuid>21ca5a2b-e9bd-4ee5-ad16-bcf6fb5293b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skinsheen Bronzer Stick'])[1]/preceding::span[2]</value>
      <webElementGuid>4d0fb473-ec8d-4df5-b198-b4bc1eeac6bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Featured']/parent::*</value>
      <webElementGuid>ae73220f-3416-434c-a00b-9236d05dc652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>6aa59e5f-438f-4b75-85cc-503d5e438181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Featured' or . = 'Featured')]</value>
      <webElementGuid>0facbf36-ca3f-46d5-90b8-80b749f474dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
