<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Specials</name>
   <tag></tag>
   <elementGuidId>f55c979f-27e8-45e0-b34a-0edea8be6321</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block_frame_special_2642']/h1/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#block_frame_special_2642 > h1.heading1 > span.maintext</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8356486d-0e2f-41ac-81ee-4f301277b169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>maintext</value>
      <webElementGuid>0d550f09-efc6-45fc-a475-8684bc2ecb3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Specials</value>
      <webElementGuid>23ae4122-0c01-4b31-afb1-7227c210d7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block_frame_special_2642&quot;)/h1[@class=&quot;heading1&quot;]/span[@class=&quot;maintext&quot;]</value>
      <webElementGuid>0797d2e7-099f-4e6c-8077-5e34bfc18f83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block_frame_special_2642']/h1/span</value>
      <webElementGuid>16d5c448-7033-4349-96bf-b4bb0be492a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$21.62'])[3]/following::span[1]</value>
      <webElementGuid>456b2b10-42a0-434a-b370-b07ae7bc8c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write Review'])[7]/following::span[1]</value>
      <webElementGuid>6286ee89-dfde-4360-ad7c-06a0ae1ddab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See Products On Sale'])[1]/preceding::span[1]</value>
      <webElementGuid>678876b6-c5e2-475f-a40f-099437e27f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Absolue Eye Precious Cells'])[2]/preceding::span[2]</value>
      <webElementGuid>5c2baa49-4f41-42d1-bd2c-bc1c7dc2ebf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div/div/h1/span</value>
      <webElementGuid>3243207c-9d22-41fb-91dc-64f5cae68e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Specials' or . = 'Specials')]</value>
      <webElementGuid>53067896-eab7-4253-8dcc-22b7151ba08c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
