<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Sort By_fa fa-th-list</name>
   <tag></tag>
   <elementGuidId>73c5fb4f-776f-403e-9a78-bf38a4c1be79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='list']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-th-list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>dc8f9231-3097-47d1-950a-4fcc8d365b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-th-list</value>
      <webElementGuid>248ca841-7977-4ad7-8c71-69f9322ff90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list&quot;)/i[@class=&quot;fa fa-th-list&quot;]</value>
      <webElementGuid>47d902fe-400e-4bd9-9e24-3c42b926a8c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='list']/i</value>
      <webElementGuid>b2233b2b-4cbb-4b03-902a-b00080793a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>e9932913-ef0c-4f9f-b061-3a56e9df3c29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
