<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Sort By_fa fa-th-list</name>
   <tag></tag>
   <elementGuidId>d0f9e407-9fe3-4817-bf38-1bb226591569</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='list']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-th-list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b59631ba-5180-4abf-94fe-a213f62b764a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-th-list</value>
      <webElementGuid>ecf46529-e7d9-4b3a-acf5-2ef1bbd0c76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list&quot;)/i[@class=&quot;fa fa-th-list&quot;]</value>
      <webElementGuid>0560b1d5-58f2-43ce-8285-4fc0f3fe429b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='list']/i</value>
      <webElementGuid>c72c3743-1c71-4529-bec7-b8a01a0183ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>c5c9c427-e30b-45e0-8ce3-d368bc1ac179</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
