<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Sort By_fa fa-th</name>
   <tag></tag>
   <elementGuidId>41644919-4c8a-4a69-a7a0-f45779a131d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='grid']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d57ae274-4ea0-42bc-806c-2c899dd52d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-th</value>
      <webElementGuid>ee11bc07-aa07-4493-898c-7f7e8f7ae491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid&quot;)/i[@class=&quot;fa fa-th&quot;]</value>
      <webElementGuid>9f664dab-30c0-4077-acc3-2d32bdb77c32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='grid']/i</value>
      <webElementGuid>73a22016-8195-4912-9cdf-a127a6754138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/i</value>
      <webElementGuid>68c9bcc9-2d8e-41fd-9dc4-5a0978f2b8c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
