<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Checkout</name>
   <tag></tag>
   <elementGuidId>9db54c1e-a299-417d-81fa-936bd44c3912</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='main_menu']/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.dropdown.open > a.top.menu_checkout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>23811401-9a78-45f2-a9c6-7342871eec93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top menu_checkout</value>
      <webElementGuid>ae0f63d8-bd32-4709-b928-83e44cd6e080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sewriveting.ca/store/index.php?rt=checkout/shipping</value>
      <webElementGuid>e6a4449c-f481-4917-b0b7-70e486083ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Checkout</value>
      <webElementGuid>3991c4d2-481c-4501-ac93-d4d47fd2e63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_menu&quot;)/li[@class=&quot;dropdown open&quot;]/a[@class=&quot;top menu_checkout&quot;]</value>
      <webElementGuid>0b463953-9967-4475-b1d2-96f66f1590a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='main_menu']/li[4]/a</value>
      <webElementGuid>195a97d2-fe80-4ebb-9b13-e4311efdc985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart'])[2]/following::a[1]</value>
      <webElementGuid>b29a4d50-2765-4b65-82b7-8cfa69f0b442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Your Order'])[2]/following::a[2]</value>
      <webElementGuid>b2b2c3a9-a39a-4e2b-b569-8c32e63f04d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://sewriveting.ca/store/index.php?rt=checkout/shipping')])[3]</value>
      <webElementGuid>f2ece701-5b39-40f1-b3be-37b19370606e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/ul/li[4]/a</value>
      <webElementGuid>c426be57-fbc3-4203-ba08-852e4efedce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sewriveting.ca/store/index.php?rt=checkout/shipping' and (text() = ' Checkout' or . = ' Checkout')]</value>
      <webElementGuid>fe609c24-6aab-4d5b-9d06-c9bf45900e3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
