<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Sort By_fa fa-th-list</name>
   <tag></tag>
   <elementGuidId>bfcc1553-61d0-40c0-919c-7bb58df02f17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='list']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-th-list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a74fb9ea-e89c-4e4b-8d20-c0190971a8e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-th-list</value>
      <webElementGuid>f3c01833-c505-4f1f-8887-3ed780163e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list&quot;)/i[@class=&quot;fa fa-th-list&quot;]</value>
      <webElementGuid>82096bba-43af-40b1-9509-4afd1a669d50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='list']/i</value>
      <webElementGuid>ca206941-bec4-4a60-8d95-f45506114a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>c4f57498-f2aa-4820-837c-6c3d01434df1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
