<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Back to top</name>
   <tag></tag>
   <elementGuidId>15f5c34a-1fa1-48d9-bd8f-842922bd2428</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='gotop']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gotop</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0419ce42-422e-4a18-be68-ef9897beb477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gotop</value>
      <webElementGuid>e6faf5b2-6745-483b-abcb-69135b43f592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>760b9158-f319-4d70-8fda-d13e189b03e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back to top</value>
      <webElementGuid>768f7cc3-bbc9-46b5-a8aa-613ffd86a353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gotop&quot;)</value>
      <webElementGuid>2ccb1024-ff7f-4c49-b495-dfa1d0c238c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='gotop']</value>
      <webElementGuid>bbab921a-0346-49d4-9e17-3a2fa41685de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='footer']/footer/a</value>
      <webElementGuid>5b045162-06c5-4f01-bb28-2d20df5c9e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Back to top')]</value>
      <webElementGuid>81864bb2-6920-4901-9b52-837f31ec50db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AbanteCart'])[1]/following::a[1]</value>
      <webElementGuid>3edd1bf5-438d-40e8-a7b5-f2619f9cac67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Back to top']/parent::*</value>
      <webElementGuid>3b219de0-067d-4b93-a24e-7a895920710a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[22]</value>
      <webElementGuid>bac72718-9b94-4ef0-9f65-0326ed74fc70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/a</value>
      <webElementGuid>106504dd-8200-4886-9ac1-73fbf9c49793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'gotop' and @href = '#' and (text() = 'Back to top' or . = 'Back to top')]</value>
      <webElementGuid>fb8df4e4-2968-49ec-a844-4dd305376fb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
