<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1020304050</name>
   <tag></tag>
   <elementGuidId>afc96980-cf1b-48f0-8b9d-82524f5c947a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='limit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#limit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7588eb00-71e6-4b04-8b88-d5b97960c413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>limit</value>
      <webElementGuid>6b71e00c-7e95-4138-aec9-a9dc765b86a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>limit</value>
      <webElementGuid>1e70e8a6-2c57-4d40-9efb-987cb429ff52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-mini</value>
      <webElementGuid>c3adc5d7-b93d-49b0-9f7b-bf4eb22c4562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>location='https://sewriveting.ca/store/index.php?rt=product/category&amp;path=68&amp;sort=date_modified-DESC&amp;page=1&amp;limit='+this.value;</value>
      <webElementGuid>dcd2d507-a2cb-4ebc-96c9-03001433d6e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			10
			20
			30
			40
			50
	</value>
      <webElementGuid>168007fe-19c2-48c4-ae54-4c6ccf5861d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;limit&quot;)</value>
      <webElementGuid>b6d1c655-8408-48bd-9914-26a5ededcf93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='limit']</value>
      <webElementGuid>a4f0d036-d442-4544-ad67-3684c35d1c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontainer']/div/div/div/div/div[4]/form/select</value>
      <webElementGuid>fa7ce8b9-4499-4392-a630-9e1128d909ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$19.06'])[4]/following::select[1]</value>
      <webElementGuid>e5608417-2b73-4300-b6fd-25478412cbcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::select[1]</value>
      <webElementGuid>3183050a-b80f-41b2-8bb8-ff86a695ad5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/form/select</value>
      <webElementGuid>72495773-03cf-433f-a1c3-42c64f15d91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'limit' and @id = 'limit' and (text() = '
			10
			20
			30
			40
			50
	' or . = '
			10
			20
			30
			40
			50
	')]</value>
      <webElementGuid>d4431880-6c5b-404b-ad65-6e6a71953275</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
