<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>432483a1-6025-40f3-ac4a-32ebbfbc0949</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='maincontainer']/div/div/div/div/div[4]/div/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-4 > a > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>468dd709-e092-4f36-8fed-ed3bfbc22e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//sewriveting.ca/store/image/thumbnails/18/6f/demo_product16_1_jpg-100091-250x250.jpg</value>
      <webElementGuid>a2b9530a-655f-4bbe-a487-899b8db65e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>27addb7f-49e5-4b62-b986-7d8c8e610947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>25f5f4f9-8dfe-4730-83e7-3fa514f3b470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontainer&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;col-md-12 col-xs-12 mt20&quot;]/div[1]/div[@class=&quot;contentpanel&quot;]/div[@class=&quot;thumbnails list row&quot;]/div[1]/div[@class=&quot;thumbnail&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/a[1]/img[1]</value>
      <webElementGuid>9ecb51fb-3769-481e-9d15-c3fab0ee8165</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontainer']/div/div/div/div/div[4]/div/div/div/div/a/img</value>
      <webElementGuid>cfb12a9a-3851-4c71-96d2-c0c18fab81c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/a/img</value>
      <webElementGuid>8169d7a5-a440-4bdb-a7d3-07f8dd00a64e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//sewriveting.ca/store/image/thumbnails/18/6f/demo_product16_1_jpg-100091-250x250.jpg']</value>
      <webElementGuid>7491f9f0-8ea6-4384-b988-23a311caa98b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
