<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sort By_list</name>
   <tag></tag>
   <elementGuidId>96db21ff-cd01-44fa-a2b6-b024da0c2db2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='list']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bbc28709-6b7e-4c62-bc6f-b85b4c9d81ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>47f561b4-fa15-4276-a1e6-fe8db12d89a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>969d0353-9960-404d-aa59-e171091b4010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list&quot;)</value>
      <webElementGuid>b6366fcc-85d0-434c-b8a9-bc27075ed7c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='list']</value>
      <webElementGuid>18eb8c1d-25ac-448d-872f-a60f98770a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontainer']/div/div/div/div/div/div/button</value>
      <webElementGuid>f9cd09eb-c62e-4914-a106-a570785a4d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gift Ideas &amp; Sets'])[3]/following::button[1]</value>
      <webElementGuid>7bb52a6d-c075-4d3d-8e5e-0d6b35631dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Night Care Crema Nera Obsidian Mineral Complex'])[1]/preceding::button[2]</value>
      <webElementGuid>f6dc9744-41c7-4858-8304-729adedd9c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/preceding::button[2]</value>
      <webElementGuid>5f2e5368-b913-493a-a019-de0205bc062b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/button</value>
      <webElementGuid>e9dbf0d9-4d06-41f8-b325-004d0796bb59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'list']</value>
      <webElementGuid>0412a7b5-ed76-4bd6-9842-1a3f6be35eca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
