<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Checkout_filter_keyword</name>
   <tag></tag>
   <elementGuidId>86a7ae36-27c3-4355-8f74-f92d9a21dfe6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter_keyword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter_keyword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5961042-1fd6-45f7-bea7-7d3bdc130bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f8734496-f258-4623-90a5-b72fea1cb1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter_keyword</value>
      <webElementGuid>ea2a4f98-e7fb-4eee-95a7-8c199b4beb24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filter_keyword</value>
      <webElementGuid>ec518401-4d98-4de0-aae5-7ef7fa91f790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b9867a37-a3ee-492c-aa63-156a38e3b56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pull-left input-medium search-query dropdown-toggle</value>
      <webElementGuid>22d2f4b8-3997-4d67-90cc-7a022413418a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Keywords</value>
      <webElementGuid>8f547b53-911b-4a83-87d3-b7276f6bd2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>27222245-7a62-4d56-8b58-0914ff0a90b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter_keyword&quot;)</value>
      <webElementGuid>41e410b9-6b47-4506-ab99-2fee76daa373</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter_keyword']</value>
      <webElementGuid>c48bf8bc-91a5-4411-aca4-528038a48515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/div/input</value>
      <webElementGuid>1d1da6c5-6b92-431f-8daf-0eb628be3853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>5f809fad-9ba0-4d89-aa71-7b21c6801902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'filter_keyword' and @name = 'filter_keyword' and @placeholder = 'Search Keywords']</value>
      <webElementGuid>ad3cc463-3025-4761-bbb6-dca846364a42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
