<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Home_fa fa-home</name>
   <tag></tag>
   <elementGuidId>cde0f4ad-17f7-4771-8e2e-37901e6d4316</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section/ul/li/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-home</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b06b561d-c6ef-4ac2-90bf-f24a1a2dedc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-home</value>
      <webElementGuid>1268883b-cb9f-431b-b75e-5ffaff3f38c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>e135fe64-71ab-4dd9-8499-11e442e43246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;product-special&quot;]/div[@class=&quot;container-fixed&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;col-md-12&quot;]/section[@class=&quot;breadcrumbs&quot;]/ul[@class=&quot;breadcrumb&quot;]/li[1]/a[1]/i[@class=&quot;fa fa-home&quot;]</value>
      <webElementGuid>41a9a834-9872-4879-80df-d48a7c9336c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/ul/li/a/i</value>
      <webElementGuid>d4ca64eb-2c2b-442d-8207-7bf7d484c511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Home']</value>
      <webElementGuid>0a43f47d-ab37-4411-9577-76ee2c62b04a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
