<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cheeks</name>
   <tag></tag>
   <elementGuidId>81151609-3301-4db8-a87c-8a2367dec9ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > div.subcategories > ul > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='categorymenu']/nav/ul/li[3]/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8e0d47ad-4082-4312-8c49-175bcd9c4f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://automationteststore.com/index.php?rt=product/category&amp;path=36_40</value>
      <webElementGuid>ecd72373-c6f3-49c3-aa36-b41eed9a2b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>    Cheeks</value>
      <webElementGuid>e74f99be-fbcb-4198-81db-1b54242ca75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categorymenu&quot;)/nav[@class=&quot;subnav&quot;]/ul[@class=&quot;nav-pills categorymenu&quot;]/li[3]/div[@class=&quot;subcategories&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>fed66431-4eac-4827-a035-f340eceaaaf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='categorymenu']/nav/ul/li[3]/div/ul/li/a</value>
      <webElementGuid>109ab644-02c7-442d-983a-0d0bf0c73e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cheeks')]</value>
      <webElementGuid>0cfbf352-120b-4d9a-9f12-260dda819373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://automationteststore.com/index.php?rt=product/category&amp;path=36_40')]</value>
      <webElementGuid>407cd50d-ea92-4cd2-900c-1814c972b048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/ul/li/a</value>
      <webElementGuid>618b755d-10a9-48dd-9ead-af6d37dcfc31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://automationteststore.com/index.php?rt=product/category&amp;path=36_40' and (text() = '    Cheeks' or . = '    Cheeks')]</value>
      <webElementGuid>3da6d9b5-559b-4481-b06a-25d5386aa093</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
