<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Facebook</name>
   <tag></tag>
   <elementGuidId>80221432-c883-45d4-8b19-d0ce0f1ebeb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.facebook</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Facebook')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9402ecef-93c9-40f7-a798-e2e462efeabe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.facebook.com</value>
      <webElementGuid>7aebbd99-857c-4f9a-9b7a-d88b0326f1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>5b18ec38-5fe3-4575-b2ce-26800ae08d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Facebook</value>
      <webElementGuid>9d9f0f2a-ac5d-43f8-8eca-3854e100d41e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>facebook</value>
      <webElementGuid>d9384c10-c969-4b16-9193-ddb94e0892e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>107b91be-bef0-4c6e-af80-e328ae492fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Facebook</value>
      <webElementGuid>7e7bbbd1-10ea-4a59-934e-49c49a6c6ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;home&quot;]/div[@class=&quot;container-fixed&quot;]/header[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;col-md-12 headerdetails&quot;]/div[@class=&quot;block_8&quot;]/div[@class=&quot;header_block&quot;]/div[@class=&quot;social_icons&quot;]/a[@class=&quot;facebook&quot;]</value>
      <webElementGuid>5aaa3647-b664-4641-9be9-54b4359b57cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Facebook')]</value>
      <webElementGuid>df1a3803-20c1-4d5c-93ab-d46e713b9828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[1]/following::a[3]</value>
      <webElementGuid>ae288412-2fc0-4530-a5b5-75dda47cf43d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[1]/preceding::a[1]</value>
      <webElementGuid>0136c4b1-dc30-4e62-b51e-dda571d4a7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Linkedin'])[1]/preceding::a[2]</value>
      <webElementGuid>a49e9360-85f4-49f2-811c-f6c4d9d072a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Facebook']/parent::*</value>
      <webElementGuid>89c48ca7-f5c9-4a90-aaa5-201d70e8141b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://www.facebook.com']</value>
      <webElementGuid>434f387c-91c7-4fac-af40-7b7270c7df21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a</value>
      <webElementGuid>319e5e91-7d97-4981-984e-86aab460af30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://www.facebook.com' and @title = 'Facebook' and (text() = 'Facebook' or . = 'Facebook')]</value>
      <webElementGuid>a24a5dd3-41c9-44b6-b23c-0a00a58b0c8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
