<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lips</name>
   <tag></tag>
   <elementGuidId>333cba2b-cc01-43a7-8ef8-22df526efefa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.subcategories > ul > li:nth-of-type(4) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='categorymenu']/nav/ul/li[3]/div/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dbe90721-ce52-4f3d-8faa-8d8c7a13e62d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://automationteststore.com/index.php?rt=product/category&amp;path=36_41</value>
      <webElementGuid>d75435b8-9b64-46ab-9b56-745411c3366b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>    Lips</value>
      <webElementGuid>4b5b09cc-cd3c-430e-a387-7e1fb3bca89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categorymenu&quot;)/nav[@class=&quot;subnav&quot;]/ul[@class=&quot;nav-pills categorymenu&quot;]/li[3]/div[@class=&quot;subcategories&quot;]/ul[1]/li[4]/a[1]</value>
      <webElementGuid>3a30d855-4750-461c-8c80-28e388e2ee13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='categorymenu']/nav/ul/li[3]/div/ul/li[4]/a</value>
      <webElementGuid>0534ed97-7ca6-4971-a2fb-4cdc0894f68e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lips')]</value>
      <webElementGuid>5b619fd8-2205-40f9-ac13-191a8f2d99e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://automationteststore.com/index.php?rt=product/category&amp;path=36_41')]</value>
      <webElementGuid>9c05d53d-1910-4358-9e3d-1eb6423c70d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/ul/li[4]/a</value>
      <webElementGuid>a000ad32-9d1a-4d3b-9914-1ead47dbdac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://automationteststore.com/index.php?rt=product/category&amp;path=36_41' and (text() = '    Lips' or . = '    Lips')]</value>
      <webElementGuid>c609f696-1795-4371-801f-3ac2516603df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
