<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>255e3f6d-7a98-4a1c-9837-d674a70d0a26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_menu > li.dropdown > ul.sub_menu.dropdown-menu > li.dropdown > a.sub.menu_login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='main_menu']/li[2]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>01a99837-9fd6-42b4-be74-1a1702d66eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub menu_login</value>
      <webElementGuid>8d3aa45b-4b31-4125-808f-a7f1eb25b150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://automationteststore.com/index.php?rt=account/login</value>
      <webElementGuid>7f87c3bf-833b-48ef-bd2a-95cd2353b855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Login</value>
      <webElementGuid>fff4a22c-5c3d-4a9a-a5aa-7d20462ce27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_menu&quot;)/li[@class=&quot;dropdown&quot;]/ul[@class=&quot;sub_menu dropdown-menu&quot;]/li[@class=&quot;dropdown&quot;]/a[@class=&quot;sub menu_login&quot;]</value>
      <webElementGuid>05abeedb-c8d9-447c-b696-8a1196984e25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='main_menu']/li[2]/ul/li/a</value>
      <webElementGuid>8004b382-769a-47de-8b70-dbe757411bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[2]/following::a[1]</value>
      <webElementGuid>6ed76b32-d68b-4c85-aec4-c161fbaa425b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specials'])[2]/following::a[2]</value>
      <webElementGuid>426c816c-827b-4083-8163-85200bedccfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Your Order'])[2]/preceding::a[1]</value>
      <webElementGuid>ca31538d-066a-4f56-b921-9c51fff21adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://automationteststore.com/index.php?rt=account/login')])[3]</value>
      <webElementGuid>83f5fad3-10cf-4652-a87c-2b12d9b6367d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/ul/li[2]/ul/li/a</value>
      <webElementGuid>cce0bffb-9c70-4f98-9bec-977c35adf5a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://automationteststore.com/index.php?rt=account/login' and (text() = ' Login' or . = ' Login')]</value>
      <webElementGuid>69f786c7-ccca-4299-a5c1-755d63449b46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
