<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Paperback</name>
   <tag></tag>
   <elementGuidId>53e32edb-dfc9-4a38-b5d8-d6b4d5199ddc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(8) > div.subcategories > ul > li:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='categorymenu']/nav/ul/li[8]/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>17d4b333-54d0-4e90-8b03-f1441b272428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://automationteststore.com/index.php?rt=product/category&amp;path=65_67</value>
      <webElementGuid>e4f95da5-2699-41d4-baf6-577a7236a7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>    Paperback</value>
      <webElementGuid>1df93ea2-266e-4674-9f8d-b481276d49f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categorymenu&quot;)/nav[@class=&quot;subnav&quot;]/ul[@class=&quot;nav-pills categorymenu&quot;]/li[8]/div[@class=&quot;subcategories&quot;]/ul[1]/li[2]/a[1]</value>
      <webElementGuid>0ebb60b7-da81-427d-ab42-cfa9babe44c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='categorymenu']/nav/ul/li[8]/div/ul/li[2]/a</value>
      <webElementGuid>2b6a66ea-261c-48c4-9509-cc00b1607837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Paperback')]</value>
      <webElementGuid>b513b7fb-9d74-43e8-b9e7-9657eaa8f39a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn Automation Testing'])[1]/preceding::a[2]</value>
      <webElementGuid>478228bb-6593-46dd-b83e-cb0ae795a58b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='the right way'])[1]/preceding::a[2]</value>
      <webElementGuid>94e03c7b-2b67-4f73-b92d-29c1b7ddd228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://automationteststore.com/index.php?rt=product/category&amp;path=65_67')]</value>
      <webElementGuid>46cf6905-3f32-4517-9fae-bdf289b92e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/div/ul/li[2]/a</value>
      <webElementGuid>713b709c-c529-4893-b580-246a20e3c3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://automationteststore.com/index.php?rt=product/category&amp;path=65_67' and (text() = '    Paperback' or . = '    Paperback')]</value>
      <webElementGuid>6b0835ef-44f6-42f9-b073-b80495b73965</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
