<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pre-Shave  Shaving</name>
   <tag></tag>
   <elementGuidId>b6ec3806-d5d8-47fc-82d0-c223246f38ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(6) > div.subcategories > ul > li:nth-of-type(3) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='categorymenu']/nav/ul/li[6]/div/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e42a2f4f-2976-4310-87ec-29d644da1ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://automationteststore.com/index.php?rt=product/category&amp;path=58_61</value>
      <webElementGuid>fb026468-ffa5-42d8-b84a-c0db5e6b27c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>    Pre-Shave &amp; Shaving</value>
      <webElementGuid>d90c4bf3-23ab-483f-bcf6-64f8b20226fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categorymenu&quot;)/nav[@class=&quot;subnav&quot;]/ul[@class=&quot;nav-pills categorymenu&quot;]/li[6]/div[@class=&quot;subcategories&quot;]/ul[1]/li[3]/a[1]</value>
      <webElementGuid>b324abbf-b045-43aa-b0dd-a8df54293914</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='categorymenu']/nav/ul/li[6]/div/ul/li[3]/a</value>
      <webElementGuid>42bbef54-1cc5-4198-b4de-79d1f8114566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pre-Shave &amp; Shaving')]</value>
      <webElementGuid>814d1ebe-a045-4ed9-b081-8022adef2316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://automationteststore.com/index.php?rt=product/category&amp;path=58_61')]</value>
      <webElementGuid>102f50dd-a95a-43be-9969-5c98a85abb21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/ul/li[3]/a</value>
      <webElementGuid>b4cd55c0-c808-4e02-94c9-1f3e3419916d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://automationteststore.com/index.php?rt=product/category&amp;path=58_61' and (text() = '    Pre-Shave &amp; Shaving' or . = '    Pre-Shave &amp; Shaving')]</value>
      <webElementGuid>27de5c8d-d9eb-4284-bd19-482464111b31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
